name: flutter_mark_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dev: ^1.0.0
  json_serializable: ^6.7.1
  json_dynamic_widget: ^6.1.0+2
  go_router: ^10.0.0
  crypto: ^3.0.3

  #  crypto
  encrypt_dart_package:
    git:
      url : https://github.com/riyan-dcosta/encrypt_dart_package.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  test: ^1.24.1
  mockito: ^5.4.2
  build_runner: ^2.4.6
  freezed: ^2.4.1
  go_router_builder: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/dynamic_widgets/